# Generated by Django 4.2 on 2026-04-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_customuser_company'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='company',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='accounts.company'),
            preserve_default=False,
        ),
    ]
