# Generated by Django 4.2 on 2026-05-06 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollments', '0002_batch_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='instructor',
        ),
        migrations.AddField(
            model_name='batch',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='batches_instructing', to=settings.AUTH_USER_MODEL),
        ),
    ]
