# Generated by Django 4.2 on 2026-05-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_remove_batch_instructor_batch_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_given',
            field=models.BooleanField(default=False),
        ),
    ]
