# Generated by Django 4.2 on 2026-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_salesrecord_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('course_title', models.CharField(max_length=255)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_name', models.CharField(max_length=100)),
                ('company_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('request_date', models.DateTimeField()),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('certificate_given', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sales Record',
                'verbose_name_plural': 'Sales Records',
                'db_table': 'enrollments_salesrecord',
                'ordering': ['-request_date'],
                'managed': False,
            },
        ),
    ]
