# Generated by Django 4.2 on 2026-05-06 12:19

from django.db import migrations, models
from django.db import migrations, models
import django.db.models.deletion

SQL_CREATE_VIEW = """
CREATE VIEW enrollments_salesrecord AS
SELECT
    e.id                                                        AS id,
    e.student_id                                                AS student_id,
    CASE
        WHEN TRIM(u.first_name || u.last_name) = ''
        THEN u.username
        ELSE TRIM(u.first_name || ' ' || u.last_name)
    END                                                         AS student_name,
    u.email                                                     AS student_email,
    b.course_id                                                 AS course_id,
    c.title                                                     AS course_title,
    c.price                                                     AS course_price,
    e.batch_id                                                  AS batch_id,
    b.name                                                      AS batch_name,
    b.company_id                                                AS company_id,
    comp.name                                                   AS company_name,
    e.status                                                    AS status,
    e.request_date                                              AS request_date,
    e.approval_date                                             AS approval_date,
    e.certificate_given                                         AS certificate_given
FROM enrollments_enrollment  e
JOIN auth_customuser         u    ON e.student_id = u.id
JOIN enrollments_batch       b    ON e.batch_id   = b.id
JOIN courses_course          c    ON b.course_id  = c.id
JOIN accounts_company        comp ON b.company_id = comp.id
"""

SQL_DROP_VIEW = "DROP VIEW IF EXISTS enrollments_salesrecord"


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_company_ssl_commerce_key_company_ssl_commerce_secret_and_more'),
        ('enrollments', '0006_salesrecord'),
    ]

    operations = [
        migrations.RunSQL(SQL_DROP_VIEW, SQL_CREATE_VIEW),
        migrations.AddField(
            model_name='enrollment',
            name='applied_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat Discount'), ('percentage', 'Percentage Discount')], default='percentage', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 10 for 10%) or Flat Amount', max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('max_limit', models.IntegerField(blank=True, help_text='Maximum number of uses', null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, help_text='Leave blank to apply to all batches in the company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='enrollments.batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'enrollments_coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='enrollments.coupon'),
        ),
        migrations.RunSQL(SQL_CREATE_VIEW, SQL_DROP_VIEW),
    ]
