# Generated by Django 4.2 on 2026-05-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0009_salesrecord_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Transaction ID / payment gateway reference for future use', max_length=255, null=True),
        ),
    ]
