# Generated by Django 4.2 on 2026-05-12 05:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0010_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_allowed',
            field=models.BooleanField(default=False, help_text='Admin must enable this before student can view/generate certificate.'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_number',
            field=models.CharField(blank=True, help_text='Human-readable certificate number.', max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_pdf',
            field=models.FileField(blank=True, help_text='Generated certificate PDF. Created on first student click.', null=True, upload_to='certificates/issued/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public unique ID for certificate verification URL.', unique=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='certificate_given',
            field=models.BooleanField(default=False, help_text='True after certificate PDF has been generated first time.'),
        ),
    ]
