# Generated by Django 4.2 on 2026-05-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0011_enrollment_certificate_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_end_period',
            field=models.CharField(blank=True, help_text='End period to display on certificate (e.g., "March 2024", "31-03-2024")', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_registration_no',
            field=models.CharField(blank=True, help_text='Registration number to display on certificate. If empty, uses certificate_number.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_start_period',
            field=models.CharField(blank=True, help_text='Start period to display on certificate (e.g., "January 2024", "01-01-2024")', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_total_months',
            field=models.CharField(blank=True, help_text='Total months/duration to display on certificate (e.g., "3 months", "6 Months")', max_length=50, null=True),
        ),
    ]
