# Generated by Django 4.2 on 2026-04-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_contact_email_company_contact_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='header_cta_link',
            new_name='cta_title',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='hero_cta_link',
            new_name='featured_title',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='header_cta_text',
            new_name='hero_primary_text',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='hero_cta_text',
            new_name='hero_secondary_text',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='favicon',
            new_name='partner_logo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='total_courses',
        ),
        migrations.AddField(
            model_name='company',
            name='cta_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='cta_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='featured_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='hero_badge',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='hero_primary_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='hero_secondary_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(default='', help_text='example.com or company.skill.jobs', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='hero_title',
            field=models.TextField(blank=True),
        ),
    ]
