# Generated by Django 4.2 on 2026-04-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_header_cta_link_company_cta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS for this company'),
        ),
        migrations.AddField(
            model_name='company',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='company',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='company',
            name='footer_scripts',
            field=models.TextField(blank=True, help_text='Scripts before </body>'),
        ),
        migrations.AddField(
            model_name='company',
            name='header_scripts',
            field=models.TextField(blank=True, help_text='Scripts inside <head> (analytics, meta, etc)'),
        ),
        migrations.AddField(
            model_name='company',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='company',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
