# Generated by Django 4.2 on 2026-04-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_custom_css_company_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_sso_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skilljobs_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skilljobs_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sso_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sso_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
