# Generated by Django 4.2 on 2026-05-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_is_sso_user_customuser_skilljobs_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ssl_commerce_key',
            field=models.CharField(blank=True, help_text='SSL Commerce Key', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='ssl_commerce_secret',
            field=models.CharField(blank=True, help_text='SSL Commerce Secret', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='ssl_commerce_url',
            field=models.URLField(blank=True, help_text='SSL Commerce Endpoint URL'),
        ),
    ]
