# Generated by Django 4.2 on 2026-05-14 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_smtpsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpsettings',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smtp_settings', to='accounts.company'),
        ),
    ]
