# Generated by Django 5.2.14 on 2026-05-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_smtpsettings_company'),
        ('accounts', '0010_company_social_links'),
    ]

    operations = [
    ]
