# Generated by Django 5.2.14 on 2026-05-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20260523_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_i2i',
            field=models.BooleanField(default=False, help_text='Allow this company to create Intern to Industry (I2I) courses'),
        ),
    ]
