# Generated by Django 4.2 on 2026-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_company_alter_question_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='answers_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot of questions and student answers at submission time'),
        ),
    ]
