# Generated by Django 4.2 on 2026-04-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'db_table': 'courses_tool',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='registration_end',
            field=models.DateTimeField(blank=True, help_text='When registrations close', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='registration_start',
            field=models.DateTimeField(blank=True, help_text='When registrations open', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, help_text='Course start date', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.tool'),
        ),
    ]
