# Generated by Django 4.2 on 2026-04-26 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_tool_course_registration_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='benefits/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_thumbnails/'),
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_sections/'),
        ),
        migrations.CreateModel(
            name='CourseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='course_gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Media',
                'verbose_name_plural': 'Course Media',
                'db_table': 'courses_coursemedia',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
