# Generated by Django. Add CourseAudience model for course-specific audience display.
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_benefit_icon_lesson_thumbnail_section_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_svg', models.TextField(blank=True, help_text='Optional SVG icon markup for this audience.')),
                ('icon_bg', models.CharField(max_length=255, blank=True, help_text="Optional CSS background for icon (e.g. 'linear-gradient(...)')")),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name': 'Course Audience',
                'verbose_name_plural': 'Course Audiences',
            },
        ),
    ]
