# Generated by Django 4.2 on 2026-05-06 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_is_sso_user_customuser_skilljobs_user_id_and_more'),
        ('courses', '0007_course_company_alter_course_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='accounts.company'),
        ),
        migrations.AlterUniqueTogether(
            name='tool',
            unique_together={('company', 'name')},
        ),
    ]
