# Generated by Django 4.2 on 2026-05-12 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_tool_company_alter_tool_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('background_image', models.ImageField(help_text='Upload certificate background image. Recommended: landscape A4 design.', upload_to='certificates/templates/')),
                ('is_default', models.BooleanField(default=False)),
                ('width_mm', models.PositiveIntegerField(default=297)),
                ('height_mm', models.PositiveIntegerField(default=210)),
                ('student_name_x', models.PositiveIntegerField(default=148)),
                ('student_name_y', models.PositiveIntegerField(default=105)),
                ('student_name_font_size', models.PositiveIntegerField(default=32)),
                ('course_title_x', models.PositiveIntegerField(default=148)),
                ('course_title_y', models.PositiveIntegerField(default=82)),
                ('course_title_font_size', models.PositiveIntegerField(default=20)),
                ('date_issued_x', models.PositiveIntegerField(default=40)),
                ('date_issued_y', models.PositiveIntegerField(default=35)),
                ('date_issued_font_size', models.PositiveIntegerField(default=11)),
                ('certificate_no_x', models.PositiveIntegerField(default=40)),
                ('certificate_no_y', models.PositiveIntegerField(default=25)),
                ('certificate_no_font_size', models.PositiveIntegerField(default=10)),
                ('qr_code_x', models.PositiveIntegerField(default=245)),
                ('qr_code_y', models.PositiveIntegerField(default=25)),
                ('qr_code_size', models.PositiveIntegerField(default=32)),
                ('primary_text_color', models.CharField(default='#111827', max_length=20)),
                ('secondary_text_color', models.CharField(default='#374151', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='courses.course')),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
                'ordering': ['course', '-is_default', 'name'],
                'unique_together': {('course', 'name')},
            },
        ),
    ]
