# Generated by Django 4.2 on 2026-05-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_certificatetemplate_custom_text_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='course_title_x',
            field=models.PositiveIntegerField(default=132),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='end_period_font_size',
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='end_period_x',
            field=models.PositiveIntegerField(default=137),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='end_period_y',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='registration_no_x',
            field=models.PositiveIntegerField(default=65),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='registration_no_y',
            field=models.PositiveIntegerField(default=175),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='start_period_font_size',
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='start_period_x',
            field=models.PositiveIntegerField(default=103),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='start_period_y',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='student_name_y',
            field=models.PositiveIntegerField(default=109),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='total_months_font_size',
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='total_months_x',
            field=models.PositiveIntegerField(default=165),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='total_months_y',
            field=models.PositiveIntegerField(default=77),
        ),
    ]
