# Generated by Django 5.2.14 on 2026-05-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_sample_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('default', 'Default (Regular Course)'), ('i2i', 'Intern to Industry (I2I)')], default='default', max_length=20),
        ),
    ]
